### ISSUE TITLE
Add all domains from social.json to the manifest.json.

### ISSUE THREAD

**Issue by kickscondor** [kickscondor/fraidycat#113]
Per @quad's comment here: https://github.com/kickscondor/fraidycat/pull/111

> The correct solution is to add all the domain roots from social.json to the manifest. IMHO, it should be a build step.
>
> Another thought: investigate using optional_permissions to reduce the total number of permissions granted at once.

This is to solve the `NetworkError` when subscribing to Instagram, Twitter, etc.

**Comment by kickscondor** [comment]
Thinking about it - I may not make whitelisting part of the build step. Since there may be exceptions to this rule - feeds that get blocked for instance, that aren't listed in social.json. We'll see how 1.1.3 goes.

**Comment by makeworld-the-better-one** [comment]
Wait, so is this happening? Will I be able to re-enable Strict tracking protection in future releases?

**Comment by kickscondor** [comment]
Yes - glad you asked. The Strict Tracking conflicts I am aware of are fixed. The update will go out tonight or tomorrow. I'm just working through debugging. Apologies that this has taken me so long!

(I also closed this because I am not following the advice of this thread for the time being - it turns out that not all social.json domains need to be whitelisted and some not listed in social.json do. So I'd rather keep the lists separate for now.)

**Comment by ksrm** [comment]
Did the update go out? I still get the NetworkError with strict tracking protection.

**Comment by kickscondor** [comment]
Okie - the update is out now.

**Comment by insanity54** [comment]
I'm still seeing the NetworkError issue in FF on Linux with Strict Tracking Protection.

![Screenshot from 2020-07-29 13-02-56](https://user-images.githubusercontent.com/670375/88847678-36a35a80-d19c-11ea-86e1-45fe61561a98.png)

**Comment by medicinecal** [comment]
Ok I will look at this. Thank you.

**Comment by medicinecal** [comment]
Somehow this needs to change - to allow Fraidycat to contact these sites that Strict Tracking is blocking. I think I am going to need to detect Strict Tracking and alert users how to turn it off for Fraidycat. Otherwise, it'll just have to disallow subscribing to Twitter.

**Comment by quad** [comment]
Works for me on FF 79.0 with STS. @insanity54 can you show your console logs?

**Comment by insanity54** [comment]
@quad I checked my FF version and it looks like I'm behind at version 73.0.1. Here's what my console slows. There is no console activity when I click the Save button, what is displayed below is all just from the page load.

![Screenshot from 2020-08-14 07-46-11](https://user-images.githubusercontent.com/670375/90261840-5f655a00-de02-11ea-9ebd-90d09054071c.png)

**Comment by insanity54** [comment]
I upgraded to FF 78.0.2. I'm no longer affected by this issue.
